name: Deploy Laravel to VPS

on:
  push:
    branches:
      - main-local

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/apps/BackEnd-SikapinSebelas
            
            git pull origin main-local
            
            composer install --no-dev --optimize-autoloader
            
            php artisan down || true
            
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            rsync -av --delete ./ /home/IDN2306510507/web/sjuwara.student.smkn11bdg.sch.id/public_html/BackEnd-SikapinSebelas/
            
            php artisan up
